In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression


In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/4_save_model/homeprices.csv')
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
df.isnull()

area  price
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False

In [4]:
df.shape

(5, 2)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   area    5 non-null      int64
 1   price   5 non-null      int64
dtypes: int64(2)
memory usage: 208.0 bytes


In [6]:
df.describe()

area          price
count     5.000000       5.000000
mean   3280.000000  626000.000000
std     540.370243   74949.983322
min    2600.000000  550000.000000
25%    3000.000000  565000.000000
50%    3200.000000  610000.000000
75%    3600.000000  680000.000000
max    4000.000000  725000.000000

In [7]:
model=LinearRegression()

In [8]:
model.fit(df[['area']],df['price'])

LinearRegression()

In [9]:
model.coef_

array([135.78767123])

In [10]:
model.intercept_

180616.43835616432

In [11]:
model.predict([[5000]])

array([859554.79452055])

# Save model to a file using python Pickle

In [12]:
import pickle

In [13]:
with open("model_pickle",'wb') as f:
    pickle.dump(model,f)

In [14]:
#Load Save Model

with open("model_pickle",'rb') as f:
    model=pickle.load(f)

In [15]:
model.coef_

array([135.78767123])

In [16]:
model.predict([[5000]])

array([859554.79452055])

In [17]:
model.intercept_

180616.43835616432

# Save trained model using joblil

In [22]:
from joblib import dump, load

In [25]:
dump(model,'file_name.joblib')

['file_name.joblib']

In [26]:
mdl=load('file_name.joblib')

In [27]:
mdl.predict([[5000]])

array([859554.79452055])

In [28]:
mdl.coef_

array([135.78767123])

In [29]:
mdl.intercept_

180616.43835616432