In [1]:
#Importing the library
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression


In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv")
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [3]:
df.shape

(8, 4)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  6 non-null      object 
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 384.0+ bytes


In [5]:
df.describe()

test_score(out of 10)  interview_score(out of 10)    salary($)
count               7.000000                    8.000000      8.00000
mean                7.857143                    7.875000  63000.00000
std                 1.345185                    1.642081  11501.55269
min                 6.000000                    6.000000  45000.00000
25%                 7.000000                    6.750000  57500.00000
50%                 8.000000                    7.500000  63500.00000
75%                 8.500000                    9.250000  70500.00000
max                10.000000                   10.000000  80000.00000

In [6]:
df.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [7]:
df=df.rename({'test_score(out of 10)':'test_score','interview_score(out of 10)':'interview_score'},axis=1)

In [8]:
df.head()

experience  test_score  interview_score  salary($)
0        NaN         8.0                9      50000
1        NaN         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000

In [9]:
df.isnull().sum()

experience         2
test_score         1
interview_score    0
salary($)          0
dtype: int64

In [10]:
import math
test_score=math.floor(df.test_score.median())
df.test_score=df.test_score.fillna(test_score)

In [11]:
df.isnull().sum()

experience         2
test_score         0
interview_score    0
salary($)          0
dtype: int64

In [15]:
df.experience=df.experience.fillna('zero')

In [16]:
from word2number import w2n

In [17]:
df.experience=df.experience.apply(w2n.word_to_num)

In [18]:
df.head()

experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000

In [19]:
df.isnull().any()

experience         False
test_score         False
interview_score    False
salary($)          False
dtype: bool

In [26]:
reg=LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df['salary($)'])

LinearRegression()

In [27]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [28]:
reg.intercept_

17737.26346433771

In [29]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [30]:
reg.predict([[12,10,10]])

array([92002.18340611])